/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-09-01 02:55:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function mo(idx){\r\n");
      out.write("\tvar x=document.getElementsByClassName('modal'+idx);\r\n");
      out.write("\tx[0].style.display='block';\r\n");
      out.write("}\r\n");
      out.write("function c(idx){\r\n");
      out.write("\tvar x=document.getElementsByClassName('modal'+idx);\r\n");
      out.write("\tx[0].style.display='none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" value=\"모달 1\" onclick=\"mo(1)\">\r\n");
      out.write("<input type=\"button\" value=\"모달 2\" onclick=\"mo(2)\">\r\n");
      out.write("<input type=\"button\" value=\"모달 3\" onclick=\"mo(3)\">\r\n");
      out.write("<input type=\"button\" value=\"모달 4\" onclick=\"mo(4)\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 모달 창 1 -->\r\n");
      out.write("\t<div class=\"modal1 modal\"  style=\"width: 100% ; height: 100vh ; background-color: black; position: fixed; left: 0px; top:0px; opacity: 0.5; display: none; \">\r\n");
      out.write("\t\t<div class=\"modal1Div\" style=\"width: 20%; height: 20vh; background-color: white; margin: 30vh auto; \">\t\t\r\n");
      out.write("\t\t\t\t<div\t style=\"height: 80%; width: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>모달창1입니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div \tstyle=\"width: 100%; text-align: right; \">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"닫기\" style=\"margin-right: 10px;\" onclick=\"c(1)\">\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 모달 창 2 -->\r\n");
      out.write("\t<div class=\"modal2 modal\"  style=\"width: 100% ; height: 100vh ; background-color: green; position: fixed; left: 0px; top:0px; opacity: 0.5; display: none; \">\r\n");
      out.write("\t\t<div class=\"modal1Div\" style=\"width: 20%; height: 20vh; background-color: blue; margin: 30vh auto; \">\t\t\r\n");
      out.write("\t\t\t\t<div\t style=\"height: 80%; width: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>모달창 222222 입니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div \tstyle=\"width: 100%; text-align: right; \">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"닫기\" style=\"margin-right: 10px;\" onclick=\"c(2)\">\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 모달 창 3 -->\r\n");
      out.write("\t<div class=\"modal3 modal\"  style=\"width: 100% ; height: 100vh ; background-color: blue; position: fixed; left: 0px; top:0px; opacity: 0.5; display: none; \">\r\n");
      out.write("\t\t<div class=\"modal1Div\" style=\"width: 20%; height: 20vh; background-color: orange; margin: 30vh auto; \">\t\t\r\n");
      out.write("\t\t\t\t<div\t style=\"height: 80%; width: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>모달창3333 입니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div \tstyle=\"width: 100%; text-align: right; \">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"닫기\" style=\"margin-right: 10px;\" onclick=\"c(3)\">\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 모달 창 4 -->\r\n");
      out.write("\t<div class=\"modal4 modal\"  style=\"width: 100% ; height: 100vh ; background-color:purple; position: fixed; left: 0px; top:0px; opacity: 0.5; display: none; \">\r\n");
      out.write("\t\t<div class=\"modal1Div\" style=\"width: 20%; height: 20vh; background-color: red; margin: 30vh auto; \">\t\t\r\n");
      out.write("\t\t\t\t<div\t style=\"height: 80%; width: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>모달창 444444 입니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div \tstyle=\"width: 100%; text-align: right; \">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"닫기\" style=\"margin-right: 10px;\" onclick=\"c(4)\">\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
